build:
    - image: "golang:1.8.1"
      workdir: "/go/src/experimental"
      cache: false
      file: /home/kovalevskayakv/work/go/src/github.com/KristinaEtc/mold-release-test/etc/.mold.env
      commands:
        - printf "machine github.com\n\tlogin $GITHUB_TOKEN\n" > /root/.netrc
        - make dep
        - make all
artifacts:
  publish:
  images:
    - name: rt