build:
    - image: "golang:1.8.1"
      workdir: "/go/src/experimental"
      cache: false
      commands:
        - printf "machine github.com\n\tlogin $GITHUB_TOKEN\n" > /root/.netrc
        - cd /go/src/experimental
        - make dep
        - make all
